eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application.name: commodity-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scstore
    username: root
    password: root
  cloud.config:
    uri: http://localhost:8888

server:
  port: 0

