server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/destinyliu/spring-cloud-config-repo
          basedir: target/config

---
spring:
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/