spring:
  application:
    name: api-gateway

server:
  port: 5555

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  stripPrefix: false
  ignoredServices: '*'
  routes:
    commodity-api:
     serviceId: commodity-service
     path: /commodities/**
